name: Build
on:
  schedule:
    - cron: "21 21 * * *"
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "aaradhak-test"
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}
@@ -30,10 +30,10 @@
          oci: true

      - name: Push to ghcr.ioAdd commentMore actions
        uses: redhat-actions/push-to-registry@v2.6
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: "latest"
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
